"""Add recipe_image column to SavedRecipe

Revision ID: 673e207a4413
Revises: b7d52c541818
Create Date: 2024-12-15 14:50:29.310763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '673e207a4413'
down_revision = 'b7d52c541818'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_recipes', schema=None) as batch_op:
        batch_op.alter_column('recipe_image',
               existing_type=sa.VARCHAR(length=600),
               type_=sa.String(length=1000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_recipes', schema=None) as batch_op:
        batch_op.alter_column('recipe_image',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=600),
               existing_nullable=True)

    # ### end Alembic commands ###
