"""adding image for saved art

Revision ID: 7fa61e1db592
Revises: ce2058ddc269
Create Date: 2024-12-15 16:22:50.403579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fa61e1db592'
down_revision = 'ce2058ddc269'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_art', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_art', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
