"""Add likes table

Revision ID: 84f50ae93f51
Revises: 7fa61e1db592
Create Date: 2024-12-16 12:37:52.873539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84f50ae93f51'
down_revision = '7fa61e1db592'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('doodle_comments')
    op.drop_table('favorites')
    with op.batch_alter_table('saved_art', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('saved_recipes', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('recipe_image',
               existing_type=sa.VARCHAR(length=100000),
               type_=sa.String(length=10000),
               existing_nullable=True)

    with op.batch_alter_table('user_doodles', schema=None) as batch_op:
        batch_op.alter_column('doodle_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'doodles', ['doodle_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_doodles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('doodle_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('saved_recipes', schema=None) as batch_op:
        batch_op.alter_column('recipe_image',
               existing_type=sa.String(length=10000),
               type_=sa.VARCHAR(length=100000),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('saved_art', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table('favorites',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='favorites_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorites_pkey')
    )
    op.create_table('doodle_comments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('doodle_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['doodle_id'], ['user_doodles.id'], name='doodle_comments_doodle_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='doodle_comments_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='doodle_comments_pkey')
    )
    op.drop_table('comments')
    # ### end Alembic commands ###
