"""Add title column to saved_recipes

Revision ID: 8934ab35c83b
Revises: 86e229698490
Create Date: 2024-12-18 11:08:13.985556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8934ab35c83b'
down_revision = '86e229698490'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('saved_recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(), nullable=False))
        batch_op.drop_column('label')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('title')

    # ### end Alembic commands ###
