"""Change SavedArt.id to String

Revision ID: b19f9243bdc3
Revises: 511ee08326be
Create Date: 2024-12-17 11:54:31.485098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b19f9243bdc3'
down_revision = '511ee08326be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_art', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)

    with op.batch_alter_table('saved_images', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_image', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_images', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_user_image', ['user_id', 'image_id'])

    with op.batch_alter_table('saved_art', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
