"""Fix auto-increment for SavedArt ID

Revision ID: c455d026f709
Revises: b19f9243bdc3
Create Date: 2024-12-17 22:05:52.374086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c455d026f709'
down_revision = 'b19f9243bdc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_art', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer, 
               postgresql_using='id::integer',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('saved_art_id_seq'::regclass)"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_art', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.String(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('saved_art_id_seq'::regclass)"))

    # ### end Alembic commands ###
