"""Add recipe_image column to SavedRecipe

Revision ID: c75b179754d2
Revises: 237ce13f84dc
Create Date: 2024-12-15 14:32:05.158633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c75b179754d2'
down_revision = '237ce13f84dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipe_image', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_recipes', schema=None) as batch_op:
        batch_op.drop_column('recipe_image')

    # ### end Alembic commands ###
