name: Deploy static content to Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    permissions:
      contents: read
      pages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Deploy files
        run: |
          mkdir -p output
          cp -r * output/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
