name: Deploy static content to Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: actions/configure-pages@v2

      - name: Upload artifacts
        run: |
          mkdir -p output
          cp -r * output/
          echo "Files prepared in output/ directory."
